import { defineConfig } from "orval";

// Input is generated by `services/backend`'s `gen:contract` script (Phase 3/4).
export default defineConfig({
  odyssey: {
    input: "../../services/backend/openapi.json",
    output: {
      mode: "tags-split",
      target: "./src/generated",
      schemas: "./src/generated/models",
      client: "react-query",
    },
  },
});
